// default package
// Generated 2016-5-7 20:32:10 by Hibernate Tools 4.0.0.Final
package testdb;
import java.util.Date;

/**
 * ShopSaleDefId generated by hbm2java
 */
public class ShopSaleDefId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7521569711130035224L;
	private Integer ShopId;
	private Integer ShopSaleId;
	private Date BeginTime;

	public ShopSaleDefId() {
	}

	public ShopSaleDefId(Integer ShopId, Integer ShopSaleId, Date BeginTime) {
		this.ShopId = ShopId;
		this.ShopSaleId = ShopSaleId;
		this.BeginTime = BeginTime;
	}

	public Integer getShopId() {
		return this.ShopId;
	}

	public void setShopId(Integer ShopId) {
		this.ShopId = ShopId;
	}

	public Integer getShopSaleId() {
		return this.ShopSaleId;
	}

	public void setShopSaleId(Integer ShopSaleId) {
		this.ShopSaleId = ShopSaleId;
	}

	public Date getBeginTime() {
		return this.BeginTime;
	}

	public void setBeginTime(Date BeginTime) {
		this.BeginTime = BeginTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ShopSaleDefId))
			return false;
		ShopSaleDefId castOther = (ShopSaleDefId) other;

		return ((this.getShopId() == castOther.getShopId()) || (this.getShopId() != null
				&& castOther.getShopId() != null && this.getShopId().equals(castOther.getShopId())))
				&& ((this.getShopSaleId() == castOther.getShopSaleId()) || (this.getShopSaleId() != null
						&& castOther.getShopSaleId() != null && this.getShopSaleId().equals(castOther.getShopSaleId())))
				&& ((this.getBeginTime() == castOther.getBeginTime()) || (this.getBeginTime() != null
						&& castOther.getBeginTime() != null && this.getBeginTime().equals(castOther.getBeginTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getShopId() == null ? 0 : this.getShopId().hashCode());
		result = 37 * result + (getShopSaleId() == null ? 0 : this.getShopSaleId().hashCode());
		result = 37 * result + (getBeginTime() == null ? 0 : this.getBeginTime().hashCode());
		return result;
	}

}
