// default package
// Generated 2016-5-8 10:48:16 by Hibernate Tools 4.3.1.Final
package testdb;
import java.util.Date;

/**
 * ShopSaleDef generated by hbm2java
 */
public class ShopSaleDef implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 517892570319227894L;
	private ShopSaleDefId id;
	private Integer maxMoney;
	private Integer userLimitMoney;
	private Integer saleMode;
	private Date beginTime;
	private Date endTime;

	public ShopSaleDef() {
	}

	public ShopSaleDef(ShopSaleDefId id, Integer maxMoney, Integer userLimitMoney, Integer saleMode, Date beginTime,
			Date endTime) {
		this.id = id;
		this.maxMoney = maxMoney;
		this.userLimitMoney = userLimitMoney;
		this.saleMode = saleMode;
		this.beginTime = beginTime;
		this.endTime = endTime;
	}

	public ShopSaleDefId getId() {
		return this.id;
	}

	public void setId(ShopSaleDefId id) {
		this.id = id;
	}

	public Integer getMaxMoney() {
		return this.maxMoney;
	}

	public void setMaxMoney(Integer maxMoney) {
		this.maxMoney = maxMoney;
	}

	public Integer getUserLimitMoney() {
		return this.userLimitMoney;
	}

	public void setUserLimitMoney(Integer userLimitMoney) {
		this.userLimitMoney = userLimitMoney;
	}

	public Integer getSaleMode() {
		return this.saleMode;
	}

	public void setSaleMode(Integer saleMode) {
		this.saleMode = saleMode;
	}

	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

}
